### ISSUE TITLE
MITMDNS still deletes/creates new config

### ISSUE THREAD

**Issue by Jump-Suit** [GitHubProUser67/MultiServer3#52]
This is getting FRUSTRATING... this program keeps deleting/creating new routes.txt deleting my existing edits...

**Comment by GitHubProUser67** [comment]
This is strange that problem you have, on what platform it happens and how can we reproduce ir? I checked code and nothing write in that area.

**Comment by Jump-Suit** [comment]
I caught this in this middle of me rerunning MITMDNS.exe on Windows 10 x64 bit. Not during a recompile, just rerunning the exe.
I checked my static followed and noticed my route.txt file was missing, then it got regenerated.

**Comment by GitHubProUser67** [comment]
I did some minor changes which should improve the situation, can you test again?

**Comment by GitHubProUser67** [comment]
Issue closed, until further notice, fixed in this commit : https://github.com/GitHubProUser67/MultiServer3/commit/f939970a8441bbc45137134003ceaed5ce2d7724.
