### ISSUE TITLE
DNS Server will occasionally stop properly responding to clients  (High-Priority)

### ISSUE THREAD

**Issue by Jump-Suit** [GitHubProUser67/MultiServer3#55]
Updated MITMDNS to latest commit yesterday during server maintenance, now it periodically stops responding in Docker and eventually stops accepting new or existing requests.

**Comment by GitHubProUser67** [comment]
I re-codded the software entierly. It should be fine now.

**Comment by Jump-Suit** [comment]
Still in testing ^^

**Comment by GitHubProUser67** [comment]
Seems to have been resolved since.
