### ISSUE TITLE
Any contact with DarkAgent?

### ISSUE THREAD

**Issue by EmilyBondevik** [GitHubProUser67/MultiServer3#63]
I heard from another person that DarkAgent has an emulator for PRUDP, which we are in need of for an old mmo we are trying to restore. Is there any contact with DarkAgent?

**Comment by GitHubProUser67** [comment]
Hello, turns out I use a generic github pseudo because it wasn't available ^^.

**Comment by GitHubProUser67** [comment]
Here is my main discord link if you wanna talk https://discord.gg/4EqsEAQn I accept DMs in theory, if not, please ping me here.

**Comment by EmilyBondevik** [comment]
> Here is my main discord link if you wanna talk https://discord.gg/4EqsEAQn I accept DMs in theory, if not, please ping me here.

Sent you a message!
