### ISSUE TITLE
Entire SSFW Avatar PR is gone from Main

### ISSUE THREAD

**Issue by Jump-Suit** [GitHubProUser67/MultiServer3#69]
https://github.com/GitHubProUser67/MultiServer3/pull/24/files It has come to my attention that my code to support avatars is now gone.
i would do a PR (Again) but I suspect it'll get worked on with better implementation than I.

**Comment by GitHubProUser67** [comment]
Gotcha, I will add it back at next commit update I do, but it's strange it got scrapped like this.
